services:
  mc-server:
    build:
      context: .
    ports:
      - "${HOST_PORT:-8888}:25565"
    volumes:
      - mc-data:/data
    environment:
      EULA: ${EULA}
      JAVA_OPTS: ${JAVA_OPTS}
    restart: on-failure


volumes:
  mc-data: